# _config.yml
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Кружок промышленного программирования 239"
logo: /assets/img/logo.png

collections:
  students:
    sort_by: lastname
  tutors:
    sort_by: lastname
